import { Lora, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const lora = Lora({ subsets: ["latin"], variable: "--font-lora" });
const nunito = Nunito({
  subsets: ["latin"],

  variable: "--font-nunito",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${nunito.variable} font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
